name: 'Deploy to PROD'

on:
  workflow_dispatch:

jobs:
  deploy_frontend:
    name: 'Deploy Frontend'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: 'Checkout Github Repo'
        uses: actions/checkout@v3
      - name: Install Root Dependencies
        run: yarn
      - name: Install React App Dependencies
        run: |
          cd frontend
          yarn
      - name: Create .env File Locally
        run: |
          cd frontend
          echo "${{secrets.ENV_FRONTEND }}" > .env
        env:
          ENV_FRONTEND: ${{secrets.ENV_FRONTEND}}
      - name: Create firebase.json File Locally
        run: cp firebase.prod.json firebase.json
      - name: Get Version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Build React Application
        run: |
          cd frontend
          REACT_APP_VERSION='${{ steps.package-version.outputs.current-version}}' yarn run build
      - name: Initialize Firebase Project
        uses: docker://w9jds/firebase-action:master
        with:
          args: use prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy React App
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only hosting:sharingexcess
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      # - name: Create Sentry release
      #   uses: getsentry/action-release@v1
      #   env:
      #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #     SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      #     SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      #   with:
      #     environment: 'production'
      #     version: ${{ steps.package-version.outputs.current-version}}
      #     set_commits: 'skip'

  deploy_backend:
    name: 'Deploy Backend'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: 'Checkout Github Repo'
        uses: actions/checkout@v3
      - name: Install Root Dependencies
        run: yarn
      - name: Install Node App Dependencies
        run: |
          cd backend
          yarn
      - name: Create .env File Locally
        run: |
          cd backend
          echo "${{secrets.ENV_BACKEND }}" > .env
      - name: Create firebase.json File Locally
        run: cp firebase.prod.json firebase.json
      - name: Initialize Firebase Project
        uses: docker://w9jds/firebase-action:master
        with:
          args: use prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy Firebase Functions
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy Node API
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only hosting:sharingexcess-api
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy Firestore Security Rules
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only firestore:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
